"""Multi-site federation between wgflow instances (v4.0).

Two wgflow instances pair to form a WireGuard tunnel between their gateway
boxes — distinct from client peers, allocated on a separate overlay subnet
(SETTINGS.federation_subnet, default 10.99.0.0/24). After the link is up,
each side can reach the other's panel HTTPS+WS ports privately.

State machine (responder side):

    [no token]   ─┐
                  │  POST /api/federation/links/pair (operator action)
                  ▼
    [pending token, ttl=10min]
                  │
                  │  POST /api/federation/handshake from initiator,
                  │  with valid one-time code → consume token
                  ▼
    [link row inserted, status=pending]
                  │
                  │  wg syncconf → kernel peer added → first WG handshake
                  │  observed via wg show
                  ▼
    [status=established]

State machine (initiator side):

    operator pastes pair URL
                  │
                  │  POST /api/federation/links/connect (operator action)
                  │   ├── parse URL, generate per-link keypair, alloc fed_addr
                  │   └── POST to remote /api/federation/handshake (TLS, WebPKI)
                  │       ├── on 200: persist link row, replay state, return ok
                  │       └── on error: surface to operator, no DB row written
                  ▼
    [link row inserted, status=pending]
                  │
                  │  wg syncconf → first handshake
                  ▼
    [status=established]

Trust model (v4.0): full panel-trust between paired wgflows. Operators are
expected to own both ends of every link they create. iptables rules at the
gateway prevent federated peers from FORWARDing through to client peers, so
even with full trust, a compromised remote wgflow cannot transit our client
traffic — it can only reach our box's own services.

TLS: WebPKI only in v4.0. The handshake uses httpx with default cert
verification. If you run wgflow's panel behind a self-signed cert and need
federation, that's on the v5 backlog (per-link SPKI pin + identity cert).
"""
from __future__ import annotations

import ipaddress
import re
import secrets
import threading
import time
import urllib.parse
from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

import httpx

from .config import SETTINGS
from . import wg_manager as wg


# ---------------------------------------------------------------------------
# Pairing token store (in-memory, responder side)
# ---------------------------------------------------------------------------
# A pending token is generated by the responder when the operator clicks
# "Generate pairing token". It's a single-use, time-limited credential the
# initiator presents on /api/federation/handshake to prove the operator on
# both ends agreed to this pairing. We hold it in memory only — losing it
# on restart is fine, the operator just generates another.

PAIRING_TOKEN_TTL_SECONDS = 600        # 10 minutes
PAIRING_RATE_LIMIT_PER_MIN = 10        # max handshake attempts/min/source-IP


@dataclass
class _PendingToken:
    code: str                          # 32-byte hex
    name_hint: str                     # operator-supplied label for the link
    created_at: float


class _TokenStore:
    """In-memory pending-pairing-token registry.

    There is at most one pending token at any given time on the responder
    side. Generating a new one supersedes any previous pending token —
    matches operator intuition ("the latest one I copied is the one I'll
    paste"). If you need parallel pairings for some reason, that's a v5
    feature.
    """

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._current: Optional[_PendingToken] = None
        # Per-source-IP rate limiter for /api/federation/handshake. Maps
        # IP → list of attempt timestamps within the last 60s.
        self._attempts: Dict[str, List[float]] = {}

    def issue(self, name_hint: str) -> _PendingToken:
        """Mint a new pairing code, replacing any existing pending one."""
        token = _PendingToken(
            code=secrets.token_hex(32),
            name_hint=name_hint.strip()[:64],
            created_at=time.time(),
        )
        with self._lock:
            self._current = token
        return token

    def peek(self) -> Optional[_PendingToken]:
        """Return the current pending token if not expired, else None.

        Does NOT consume. Used by the UI to show whether a pairing window
        is open and how long is left.
        """
        with self._lock:
            tok = self._current
            if tok is None:
                return None
            if time.time() - tok.created_at > PAIRING_TOKEN_TTL_SECONDS:
                self._current = None
                return None
            return tok

    def consume(self, presented_code: str) -> Optional[_PendingToken]:
        """Constant-time check + single-use consume.

        Returns the pending token if `presented_code` matches and the
        window is still open. None on any mismatch — no distinction
        between "no pending token", "wrong code", and "expired" so an
        attacker can't probe.
        """
        with self._lock:
            tok = self._current
            if tok is None:
                return None
            if time.time() - tok.created_at > PAIRING_TOKEN_TTL_SECONDS:
                self._current = None
                return None
            # Constant-time compare.
            if not secrets.compare_digest(tok.code, presented_code):
                return None
            self._current = None
            return tok

    def cancel(self) -> None:
        """Operator-initiated cancellation of the current pending token."""
        with self._lock:
            self._current = None

    def check_rate_limit(self, source_ip: str) -> bool:
        """Return True if this source is within the rate budget.

        Window: 60 seconds. Limit: PAIRING_RATE_LIMIT_PER_MIN attempts.
        Called from the receiving side of /api/federation/handshake to
        defend against brute-force code guessing during a pairing window.
        """
        now = time.time()
        with self._lock:
            buf = self._attempts.setdefault(source_ip, [])
            # Drop entries older than 60s.
            buf[:] = [t for t in buf if now - t < 60.0]
            if len(buf) >= PAIRING_RATE_LIMIT_PER_MIN:
                return False
            buf.append(now)
            return True


TOKEN_STORE = _TokenStore()


# ---------------------------------------------------------------------------
# Pair-URL serialization
# ---------------------------------------------------------------------------
# The string the operator copies from the responder and pastes into the
# initiator. Format:
#
#     wgflow-pair://<panel_host>:<panel_port>/<one_time_code>
#
# Cert pinning is intentionally NOT included in v4.0 — we rely on WebPKI
# verification when the initiator does the outbound POST. SPKI pinning
# was discussed and deferred (would require operators to use Let's Encrypt
# --reuse-key, which most don't).

_PAIR_URL_SCHEME = "wgflow-pair"


def build_pair_url(panel_endpoint: str, code: str) -> str:
    """Compose the pasteable URL the operator hands to the other side."""
    if "://" in panel_endpoint:
        # Operator pasted a full URL into the panel-endpoint field; strip
        # the scheme so we don't end up with wgflow-pair://https://...
        panel_endpoint = panel_endpoint.split("://", 1)[1]
    return f"{_PAIR_URL_SCHEME}://{panel_endpoint.strip('/')}/{code}"


_PAIR_URL_RE = re.compile(
    rf"^{_PAIR_URL_SCHEME}://([^/]+)/([A-Fa-f0-9]+)$"
)


@dataclass
class ParsedPairURL:
    panel_endpoint: str    # "host:port"
    code: str


def parse_pair_url(url: str) -> ParsedPairURL:
    """Parse the URL the initiator's operator pastes. Raises ValueError."""
    m = _PAIR_URL_RE.match(url.strip())
    if not m:
        raise ValueError("not a wgflow-pair URL")
    panel = m.group(1)
    code = m.group(2)
    if len(code) < 16:
        # Reject suspiciously short codes — defensive against typo'd or
        # truncated paste.
        raise ValueError("pairing code too short")
    return ParsedPairURL(panel_endpoint=panel, code=code)


# ---------------------------------------------------------------------------
# Federation address allocation
# ---------------------------------------------------------------------------
# Each wgflow box has exactly one address on the federation overlay subnet,
# stored in network_settings under 'federation_local_addr'. It is allocated
# lazily — on first pairing — so a deployment that never federates never
# touches the overlay at all.
#
# Remote-side allocations are picked at handshake time, choosing the
# lowest free /32 in the subnet that isn't (a) the local address or
# (b) already used by an existing federation_links row.

def _addr_in_use(conn, addr: str) -> bool:
    """Whether `addr` (as 'x.x.x.x/32') appears in any existing link row."""
    row = conn.execute(
        "SELECT 1 FROM federation_links "
        "WHERE local_fed_addr = ? OR remote_fed_addr = ? LIMIT 1",
        (addr, addr),
    ).fetchone()
    return row is not None


def _local_addr(conn) -> str:
    """Read the persisted local federation address. '' if not yet allocated."""
    row = conn.execute(
        "SELECT value FROM network_settings WHERE key='federation_local_addr'"
    ).fetchone()
    return (row["value"] if row else "") or ""


def ensure_local_addr(conn) -> str:
    """Allocate (if needed) and return this box's federation /32.

    Idempotent — once allocated, subsequent calls return the same value.
    Called from both pair-token generation and connect-by-URL flows so
    whichever happens first wins.
    """
    existing = _local_addr(conn)
    if existing:
        return existing
    chosen = None
    # Pick the FIRST host in the subnet — predictable, easy to remember
    # for the operator. Skip if (somehow) already used by a remote slot.
    for host in SETTINGS.federation_subnet.hosts():
        candidate = f"{host}/32"
        if not _addr_in_use(conn, candidate):
            chosen = candidate
            break
    if chosen is None:
        raise RuntimeError("federation subnet exhausted on local allocation")
    conn.execute(
        "INSERT OR REPLACE INTO network_settings(key, value) VALUES (?, ?)",
        ("federation_local_addr", chosen),
    )
    return chosen


def allocate_remote_addr(conn) -> str:
    """Pick a free /32 in the federation subnet for a new remote link.

    Avoids our own local address and any address already claimed by an
    existing federation_links row (in either local_fed_addr or
    remote_fed_addr columns). Returned as 'x.x.x.x/32'.
    """
    local = _local_addr(conn)
    for host in SETTINGS.federation_subnet.hosts():
        candidate = f"{host}/32"
        if candidate == local:
            continue
        if _addr_in_use(conn, candidate):
            continue
        return candidate
    raise RuntimeError("federation subnet exhausted")


# ---------------------------------------------------------------------------
# Handshake (initiator → responder, outbound HTTPS)
# ---------------------------------------------------------------------------
# The initiator's operator has pasted a wgflow-pair URL. We:
#   1. Parse the URL.
#   2. Generate a per-link WG keypair + PSK.
#   3. Allocate our local fed addr (if not yet allocated) and a remote slot.
#      Wait — we don't allocate the *remote*'s address here. The responder
#      picks its own address from its own subnet view (subnets are local
#      decisions; both sides may even use different subnets). We tell the
#      remote what address WE will use; they tell us what THEY will use.
#   4. POST to /api/federation/handshake with our half of the bundle.
#   5. Receive their half. Persist a federation_links row.
#
# Returned dict mirrors the row that should be inserted by the caller; the
# actual DB write + replay is done in main.py so this module stays free of
# DB-write side effects.

HANDSHAKE_HTTP_TIMEOUT = 20.0


@dataclass
class HandshakeResult:
    """Everything the caller needs to insert a federation_links row."""
    name: str
    role: str                      # 'initiator'
    local_privkey: str
    local_pubkey: str
    remote_pubkey: str
    psk: str
    remote_wg_endpoint: str
    local_fed_addr: str
    remote_fed_addr: str
    remote_panel_endpoint: str
    remote_instance_id: str
    remote_instance_name: str


async def initiate_handshake(
    *,
    pair_url: str,
    link_name: str,
    local_fed_addr: str,
    local_instance_id: str,
    local_instance_name: str,
) -> HandshakeResult:
    """Drive the outbound side of a pairing.

    Caller is responsible for:
      - calling ensure_local_addr() before this to obtain local_fed_addr
      - persisting the returned HandshakeResult into federation_links
      - calling _replay_state_to_kernel() to install the WG peer

    Raises ValueError on bad input, httpx.HTTPError on network/TLS failure,
    RuntimeError on a remote-side rejection (response carries a message).
    """
    parsed = parse_pair_url(pair_url)

    # Generate per-link WG identity. Important: NOT the server-wide keypair
    # — each link gets its own so revoking a single link doesn't ripple.
    privkey = wg.genkey()
    pubkey = wg.pubkey(privkey)
    psk = wg.genpsk()

    body = {
        "code": parsed.code,
        "link_name_hint": link_name,
        "wg_pubkey": pubkey,
        "wg_endpoint": SETTINGS.federation_wg_endpoint,
        "psk": psk,
        "fed_addr": local_fed_addr,
        "panel_endpoint": "",     # filled by caller layer if exposing one;
                                  # for v4.0 we let the remote use the
                                  # source IP+port of this very request.
        "instance_id": local_instance_id,
        "instance_name": local_instance_name,
    }

    url = f"https://{parsed.panel_endpoint}/api/federation/handshake"

    async with httpx.AsyncClient(
        timeout=HANDSHAKE_HTTP_TIMEOUT,
        # WebPKI verification ON. Operators pairing wgflows behind self-
        # signed certs need a reverse proxy with a real cert. v5 may add
        # opt-in SPKI pinning that bypasses WebPKI for self-signed.
        verify=True,
        follow_redirects=False,
    ) as client:
        resp = await client.post(url, json=body)

    if resp.status_code != 200:
        # Surface the remote's error to the operator. We don't trust the
        # body to be JSON — could be an nginx 502 page if the panel is down.
        try:
            err = resp.json().get("detail", resp.text[:200])
        except Exception:
            err = resp.text[:200]
        raise RuntimeError(
            f"remote responded {resp.status_code}: {err}"
        )

    try:
        data = resp.json()
    except Exception as e:
        raise RuntimeError(f"remote returned non-JSON response: {e}")

    # Validate every field. Defensive — a misconfigured/older remote could
    # send back something we'd choke on later at replay time.
    required = ("wg_pubkey", "wg_endpoint", "psk_echo",
                "fed_addr", "instance_id", "instance_name")
    missing = [k for k in required if k not in data]
    if missing:
        raise RuntimeError(f"remote response missing fields: {missing}")

    # The remote echoes back the PSK we sent so we can confirm they
    # received it intact (HTTPS body integrity is already covered by TLS,
    # but this also catches the "remote rewrote our PSK" misconfiguration
    # case). If they don't echo it correctly, abort.
    if not secrets.compare_digest(data["psk_echo"], psk):
        raise RuntimeError("remote echoed mismatched PSK; aborting")

    # Sanity-check the remote's chosen fed_addr — must be a /32 in some
    # private range. We don't enforce same subnet as our own (the two
    # sides may run different overlay subnets; AllowedIPs handles routing).
    try:
        ipaddress.IPv4Interface(data["fed_addr"])
    except (ValueError, ipaddress.AddressValueError) as e:
        raise RuntimeError(f"remote sent invalid fed_addr: {e}")

    return HandshakeResult(
        name=link_name,
        role="initiator",
        local_privkey=privkey,
        local_pubkey=pubkey,
        remote_pubkey=data["wg_pubkey"],
        psk=psk,
        remote_wg_endpoint=data["wg_endpoint"],
        local_fed_addr=local_fed_addr,
        remote_fed_addr=data["fed_addr"],
        remote_panel_endpoint=parsed.panel_endpoint,
        remote_instance_id=data["instance_id"],
        remote_instance_name=data["instance_name"],
    )


# ---------------------------------------------------------------------------
# Handshake (responder side, inbound)
# ---------------------------------------------------------------------------
# Called from the FastAPI route handler. Verifies the one-time code, picks
# our half of the bundle, returns the response payload + the row to insert.

@dataclass
class IncomingHandshake:
    """Parsed + validated initiator bundle."""
    link_name_hint: str
    remote_pubkey: str
    remote_wg_endpoint: str
    psk: str
    remote_fed_addr: str
    remote_instance_id: str
    remote_instance_name: str


def parse_incoming_bundle(body: dict) -> IncomingHandshake:
    """Validate the body fields. Raises ValueError with a safe message."""
    required = ("code", "link_name_hint", "wg_pubkey", "wg_endpoint",
                "psk", "fed_addr", "instance_id", "instance_name")
    missing = [k for k in required if k not in body]
    if missing:
        raise ValueError(f"missing fields: {','.join(missing)}")

    # Loose pubkey shape check (wg pubkeys are 44 base64 chars ending with =)
    pub = body["wg_pubkey"]
    if not isinstance(pub, str) or len(pub) != 44 or not pub.endswith("="):
        raise ValueError("wg_pubkey malformed")

    # Endpoint shape check.
    ep = body["wg_endpoint"]
    if not isinstance(ep, str) or ":" not in ep:
        raise ValueError("wg_endpoint malformed")

    # Address check.
    try:
        ipaddress.IPv4Interface(body["fed_addr"])
    except (ValueError, ipaddress.AddressValueError):
        raise ValueError("fed_addr malformed")

    return IncomingHandshake(
        link_name_hint=str(body["link_name_hint"])[:64],
        remote_pubkey=pub,
        remote_wg_endpoint=ep,
        psk=body["psk"],
        remote_fed_addr=body["fed_addr"],
        remote_instance_id=str(body["instance_id"])[:64],
        remote_instance_name=str(body["instance_name"])[:64],
    )


def build_response_payload(
    *,
    local_pubkey: str,
    psk: str,
    local_fed_addr: str,
    instance_id: str,
    instance_name: str,
) -> dict:
    """Serialize the responder's reply to the initiator."""
    return {
        "wg_pubkey": local_pubkey,
        "wg_endpoint": SETTINGS.federation_wg_endpoint,
        "psk_echo": psk,                    # confirms intact PSK transit
        "fed_addr": local_fed_addr,
        "instance_id": instance_id,
        "instance_name": instance_name,
    }


# ---------------------------------------------------------------------------
# Probe
# ---------------------------------------------------------------------------
# Lightweight readback: is the remote wgflow's panel reachable from our
# side over the federation tunnel? Used by the UI to confirm the link is
# actually usable (not just that wg show reports a handshake — the kernel
# can have a "fresh" handshake while the panel HTTPS listener is dead).

PROBE_HTTP_TIMEOUT = 5.0


async def probe_remote_panel(remote_fed_addr: str) -> Tuple[bool, str]:
    """GET https://<remote_fed_ip>/healthz — return (ok, message).

    Strips the /32 mask. Doesn't follow redirects. Accepts any 2xx as ok.
    The healthz endpoint is in PUBLIC_PATHS (auth.py) so we don't need
    to authenticate over the tunnel for this — the federation tunnel
    being up is the authentication layer here.

    Note: some operators run wgflow's panel behind a reverse proxy that
    only listens on the public address, not on the federation overlay.
    In that case probe will fail even when the WG link is healthy. The
    UI distinguishes "WG handshake fresh" (green) from "WG handshake
    fresh but probe failed" (yellow with note) so the operator can tell
    which it is.
    """
    ip = remote_fed_addr.split("/", 1)[0]
    url = f"https://{ip}/healthz"
    try:
        async with httpx.AsyncClient(
            timeout=PROBE_HTTP_TIMEOUT,
            verify=False,    # over the tunnel — TLS termination on the
                             # remote panel may be self-signed if they
                             # only have a public cert for the WAN-side
                             # hostname. The tunnel itself authenticates
                             # the remote (only the paired wgflow can
                             # answer at this overlay address).
            follow_redirects=False,
        ) as client:
            r = await client.get(url)
        if 200 <= r.status_code < 300:
            return True, f"HTTP {r.status_code}"
        return False, f"HTTP {r.status_code}"
    except httpx.HTTPError as e:
        return False, type(e).__name__
    except Exception as e:
        return False, type(e).__name__


# ---------------------------------------------------------------------------
# Status reconciliation
# ---------------------------------------------------------------------------
# Read `wg show wg0 dump` and update federation_links rows whose
# remote_pubkey matches a peer with a recent handshake. Called from the
# probe endpoint and from the metrics tick (cheap — already iterating
# the dump for client peers).

# Treat a handshake as "alive" if it's within this many seconds. Same
# threshold the metrics module uses for "peer online" — keep them in
# sync so a federated link's status agrees with the live-peers panel.
HANDSHAKE_FRESH_SECONDS = 180


def reconcile_link_status(conn, dump_rows) -> int:
    """Update status/last_handshake_ts for every federation_links row.

    `dump_rows` may be either:
      - a list of dicts (from wg.show_dump()) with keys public_key
        and latest_handshake, or
      - a dict mapping pubkey → object with `latest_handshake` attr
        (from metrics._collect_peers)
    Both are accepted so callers don't need to convert.

    Returns the number of rows that flipped state. Caller doesn't need
    this value for correctness; it's useful for logging.
    """
    # Normalize to {pubkey: latest_handshake}.
    by_pub_hs: Dict[str, int] = {}
    if isinstance(dump_rows, dict):
        for pub, pm in dump_rows.items():
            by_pub_hs[pub] = getattr(pm, "latest_handshake", 0) or 0
    else:
        for r in dump_rows:
            by_pub_hs[r["public_key"]] = r.get("latest_handshake", 0) or 0
    flipped = 0
    rows = conn.execute(
        "SELECT id, remote_pubkey, status, enabled, last_handshake_ts "
        "FROM federation_links"
    ).fetchall()
    now_ts = int(time.time())
    for row in rows:
        if not row["enabled"]:
            new_status = "disabled"
            kernel_ts = None
        elif row["remote_pubkey"] not in by_pub_hs:
            # WG peer isn't in the dump at all — replay hasn't happened
            # or syncconf dropped it. Leave status as-is; replay will
            # re-add and the next tick will update.
            continue
        else:
            kernel_ts = by_pub_hs[row["remote_pubkey"]]
            if kernel_ts and now_ts - kernel_ts < HANDSHAKE_FRESH_SECONDS:
                new_status = "established"
            else:
                # Has a kernel peer entry but no recent handshake. Pending
                # if we've never seen one, failed if we used to see one
                # but stopped.
                if row["status"] in ("established", "failed"):
                    new_status = "failed"
                else:
                    new_status = "pending"

        if new_status != row["status"]:
            # Stamp last_handshake_ts only on positive transitions so a
            # link that goes established → failed retains the most recent
            # known-good handshake time for the UI to display.
            if new_status == "established" and kernel_ts:
                stamp_ts = kernel_ts
            elif new_status == "established":
                stamp_ts = now_ts
            else:
                stamp_ts = row["last_handshake_ts"]
            conn.execute(
                "UPDATE federation_links SET status=?, last_handshake_ts=? "
                "WHERE id=?",
                (new_status, stamp_ts, row["id"]),
            )
            flipped += 1
    return flipped
