"""Per-peer PowerShell installer generator + zip packager.

Renders a self-contained .ps1 script with the WireGuard config embedded as
base64. The .ps1 is then wrapped in an AES-256 encrypted zip with an
auto-generated passphrase, suitable for emailing.

Workflow:
  1. UI calls render_install_script(name, conf) -> .ps1 text with conf embedded
  2. UI calls package_install_zip(name, ps1, password) -> (zip bytes, filename)
  3. Browser downloads the zip; UI shows the passphrase to the operator
  4. Operator emails the zip and communicates the passphrase via a
     separate channel (SMS, Signal, in person)
  5. Recipient extracts with 7-Zip (native Windows zip UI does NOT support
     AES-encrypted zips), runs the .ps1, and is on the VPN

The .ps1 itself contains the peer's private key in base64 — the encrypted
zip is the only thing protecting it. This is acceptable for the email-
based distribution flow but means the .ps1 must never be distributed
unencrypted.
"""
from __future__ import annotations

import base64
import io
import re
import secrets
from typing import Tuple

import pyzipper

# ---------------------------------------------------------------------------
# Wordlist for passphrase generation. A curated subset of common short
# English words. Each word ≤ 6 characters, easy to communicate verbally
# (no homophones, no ambiguous spellings). 200+ words → ~7.6 bits/word.
# 8 words → ~61 bits, plenty against offline brute-force on AES-256 zip.
# ---------------------------------------------------------------------------

_WORDS = """
acid acre actor adult agent aim album alert alley amber angle ankle apple
arch arena army arrow ash aunt auto axis baby back bag bake band bank bar
bark barn base bath bay beam bean bear beat bed bee beef bell belly belt bench
bend berry best bet bib bid big bike bill bin bird birth bit bite black blade
blame blank blast bless blind block blood blow blue blur board boat body bold
bolt bone book boom boot born boss both bow bowl box boy brain brake branch
brand brave bread break breed brick bride brief bring broad broom brown brush
bubble buddy bug build bull bun bunch burn bus bush buyer cab cabin cake
calf call calm camp can cap car card care carry cart case cash cast cat catch
cause cave cell cent chain chair chalk champ chance change charge chart chase
chat cheap cheek cheese chef chess chest chick chief chili chin chip chirp
choice chop church cigar cinch city civic clamp clap clash class claw clay
clean clear clerk click cliff climb clip clock clog close cloth cloud clown
club coach coal coast cob code coffee coin cold color comb come cone cook
copper copy cord cork corn cost couch cough count couple court cousin cover
cowbell crab craft crane crash crawl craze crazy cream crew cried crispy
crook crop cross crow crowd crown crush crust crypt cup cure curl curry
cut cute cycle dad daily dairy daisy dance darken dash data date dawn deaf
deal death debate debit debt decaf decay decide decoy deduct deed deep
deer defrost defuse degree delete deli delta demote denial dense
"""

_WORDLIST = [w for w in _WORDS.split() if w]
assert len(_WORDLIST) >= 200, f"wordlist too short: {len(_WORDLIST)}"


def generate_passphrase(words: int = 8) -> str:
    """Generate a Diceware-style passphrase using cryptographic randomness.

    Hyphen-separated so word boundaries are unambiguous when communicated
    via SMS / verbal channels.
    """
    return "-".join(secrets.choice(_WORDLIST) for _ in range(words))


# ---------------------------------------------------------------------------
# PowerShell script template
# ---------------------------------------------------------------------------
# Two substitutions: __PEER_NAME__ and __CONF_BASE64__.
# Use str.replace (not .format) so {} characters in PowerShell are safe.

_PS1_TEMPLATE = r"""# wgflow client installer for peer: __PEER_NAME__
#
# This script is self-contained: the WireGuard configuration is embedded
# inside it (base64-encoded). On run the script:
#   1. Self-elevates to administrator
#   2. Installs the WireGuard client if it isn't already
#   3. Removes any existing tunnel named "__PEER_NAME__"
#   4. Writes the embedded config and starts the tunnel
#
# Re-run any time the wgflow admin sends you a new copy.
#
# WARNING: this script contains your VPN private key. Treat it like a
# password — do not share, do not commit to source control. The encrypted
# zip you received this in is the protection; once extracted, this file
# is sensitive.
#
# Generated by wgflow.

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Self-elevate to administrator if we aren't already.
# ---------------------------------------------------------------------------
function Test-IsAdmin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

if (-not (Test-IsAdmin)) {
    Write-Host "Re-launching with administrator privileges..." -ForegroundColor Yellow
    $argList = @(
        '-NoProfile',
        '-ExecutionPolicy', 'Bypass',
        '-File', "`"$PSCommandPath`""
    )
    Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $argList
    exit
}

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
$PeerName     = '__PEER_NAME__'
$ConfPath     = Join-Path $env:TEMP "$PeerName.conf"
$WgInstallDir = "$env:ProgramFiles\WireGuard"
$WgExe        = "$WgInstallDir\wireguard.exe"
$InstallerUrl = 'https://download.wireguard.com/windows-client/wireguard-installer.exe'

# Embedded WireGuard config (base64).
$ConfBase64 = @'
__CONF_BASE64__
'@

Write-Host ""
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host "  wgflow client installer" -ForegroundColor Cyan
Write-Host "  peer: $PeerName" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host ""

# ---------------------------------------------------------------------------
# 1. Install WireGuard if missing
# ---------------------------------------------------------------------------
function Test-WireGuardInstalled {
    if (Test-Path -LiteralPath $WgExe) { return $true }
    $regKeys = @(
        'HKLM:\SOFTWARE\WireGuard',
        'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WireGuard'
    )
    foreach ($k in $regKeys) {
        if (Test-Path -LiteralPath $k) { return $true }
    }
    return $false
}

if (Test-WireGuardInstalled) {
    Write-Host "[1/4] WireGuard is already installed." -ForegroundColor Green
} else {
    Write-Host "[1/4] WireGuard not found - downloading the latest installer..." -ForegroundColor Yellow
    $tempInstaller = Join-Path $env:TEMP 'wireguard-installer.exe'
    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $InstallerUrl -OutFile $tempInstaller -UseBasicParsing
    } catch {
        Write-Host "ERROR: failed to download WireGuard installer." -ForegroundColor Red
        Write-Host "  $($_.Exception.Message)" -ForegroundColor Red
        Read-Host "Press Enter to exit"
        exit 1
    }

    Write-Host "      installing silently (this may take 30-60 seconds)..." -ForegroundColor Yellow
    $proc = Start-Process -FilePath $tempInstaller -ArgumentList '/S' -Wait -PassThru
    Remove-Item -LiteralPath $tempInstaller -Force -ErrorAction SilentlyContinue

    if ($proc.ExitCode -ne 0) {
        Write-Host "ERROR: WireGuard installer exited with code $($proc.ExitCode)." -ForegroundColor Red
        Read-Host "Press Enter to exit"
        exit 1
    }

    if (-not (Test-Path -LiteralPath $WgExe)) {
        Write-Host "ERROR: installer ran but $WgExe is still missing." -ForegroundColor Red
        Read-Host "Press Enter to exit"
        exit 1
    }
    Write-Host "      installed OK." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 2. Decode + write the embedded config
# ---------------------------------------------------------------------------
Write-Host "[2/4] Writing config to $ConfPath..." -ForegroundColor Yellow
try {
    $confBytes = [Convert]::FromBase64String($ConfBase64.Trim())
    [System.IO.File]::WriteAllBytes($ConfPath, $confBytes)
} catch {
    Write-Host "ERROR: failed to decode embedded config: $($_.Exception.Message)" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

# ---------------------------------------------------------------------------
# 3. Remove any existing tunnel with this name (idempotent upgrade path)
# ---------------------------------------------------------------------------
Write-Host "[3/4] Removing any existing tunnel named '$PeerName'..." -ForegroundColor Yellow
$null = & $WgExe '/uninstalltunnelservice' $PeerName 2>&1
Start-Sleep -Seconds 2

# ---------------------------------------------------------------------------
# 4. Install + start the new tunnel
# ---------------------------------------------------------------------------
Write-Host "[4/4] Installing tunnel..." -ForegroundColor Yellow
$installOutput = & $WgExe '/installtunnelservice' $ConfPath 2>&1
$installExit = $LASTEXITCODE

# Wipe the temp conf — WireGuard's tunnel service has its own copy now,
# and we don't want the unencrypted .conf left in %TEMP%.
Remove-Item -LiteralPath $ConfPath -Force -ErrorAction SilentlyContinue

if ($installExit -ne 0) {
    Write-Host "ERROR: tunnel install failed (exit $installExit):" -ForegroundColor Red
    Write-Host "  $installOutput" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "==============================================" -ForegroundColor Green
Write-Host "  SUCCESS" -ForegroundColor Green
Write-Host "  Tunnel '$PeerName' is installed and active." -ForegroundColor Green
Write-Host "  Open the WireGuard app to view status." -ForegroundColor Green
Write-Host "==============================================" -ForegroundColor Green
Write-Host ""
Read-Host "Press Enter to exit"
"""


_SAFE_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+$")


def render_install_script(peer_name: str, conf_text: str) -> str:
    """Render a self-contained .ps1 with the WireGuard config embedded as base64.

    Raises ValueError on unsafe peer names (anything that could break the
    PowerShell single-quote literal we interpolate it into).
    """
    if not peer_name or not _SAFE_NAME_RE.match(peer_name):
        raise ValueError(
            f"unsafe peer name {peer_name!r} for installer script — must "
            f"match {_SAFE_NAME_RE.pattern}"
        )
    raw_b64 = base64.b64encode(conf_text.encode("utf-8")).decode("ascii")
    wrapped = "\n".join(raw_b64[i:i + 76] for i in range(0, len(raw_b64), 76))
    return (
        _PS1_TEMPLATE
        .replace("__PEER_NAME__", peer_name)
        .replace("__CONF_BASE64__", wrapped)
    )


# ---------------------------------------------------------------------------
# Zip packaging — AES-256
# ---------------------------------------------------------------------------

def package_install_zip(
    peer_name: str, ps1_text: str, password: str
) -> Tuple[bytes, str]:
    """Wrap the .ps1 in a single-entry AES-256 encrypted zip.

    AES-256 is required because the .ps1 contains the peer's private key
    and legacy ZipCrypto is recoverable in seconds via known-plaintext
    attacks (a script with a predictable preamble is the textbook case).

    Trade-off: native Windows zip UI cannot extract AES-encrypted zips;
    recipients need 7-Zip installed. The wgflow UI surfaces this fact
    when showing the passphrase.

    Returns (zip_bytes, inner_filename).
    """
    buf = io.BytesIO()
    inner_filename = f"{peer_name}-install.ps1"

    with pyzipper.AESZipFile(
        buf, mode="w",
        compression=pyzipper.ZIP_DEFLATED,
        encryption=pyzipper.WZ_AES,
    ) as zf:
        zf.setpassword(password.encode("utf-8"))
        zf.writestr(inner_filename, ps1_text)

    return buf.getvalue(), inner_filename


# ---------------------------------------------------------------------------
# v4.4.0 — user-context installer (.ps1, no zip)
# ---------------------------------------------------------------------------
#
# Different threat model from the encrypted-zip flow above:
#
#   - Recipient is the wgflow operator themselves (or someone they trust),
#     logged into the panel, downloading the .ps1 directly over HTTPS.
#   - No insecure distribution channel — the transport is the panel itself.
#   - The .ps1 is delivered in plaintext (still contains the peer private
#     key, but the HTTPS channel protects it in transit). The recipient
#     runs it on their own machine, where the private key needs to live
#     anyway in WireGuard's config store.
#
# Differences from _PS1_TEMPLATE above:
#
#   - Runs user-context FIRST, elevates only when needed for the actual
#     service installs. The unelevated phase does checks, backup,
#     directory setup. UAC appears only for the install/uninstall service
#     calls themselves.
#   - Smarter detection — looks for WireGuard in machine-wide AND per-user
#     installs, checks the registry uninstall entries by name not just
#     by exact path.
#   - Backups the existing tunnel config (if any) to
#     %LOCALAPPDATA%\wgflow-backups\<peer>-<timestamp>.conf BEFORE
#     overwriting. WireGuard's own copy under Program Files is
#     admin-only, so the user-space backup is the recoverable one.
#   - Structured logging to %LOCALAPPDATA%\wgflow\install.log
#     (rotated: keep last 5).
#   - -Action flag: Install (default), Uninstall, Update.
#   - -RemoveWireGuardClient flag for Uninstall: removes the WireGuard
#     client entirely (with confirmation prompt, since this also removes
#     any non-wgflow tunnels the user might have).
#   - Returns proper exit codes (0 success, non-zero with category).
#   - No final Read-Host (the script is meant to be runnable from an
#     existing terminal/Run dialog without leaving a hanging window).

_PS1_USER_TEMPLATE = r"""<#
.SYNOPSIS
    wgflow client installer for peer: __PEER_NAME__

.DESCRIPTION
    Installs or removes a WireGuard tunnel for this peer. The peer's
    WireGuard configuration is embedded in this script as base64.

    On Install (default): downloads WireGuard if not present, backs up
    any existing tunnel with the same name, writes the new config, and
    starts the tunnel as a Windows service. The script elevates to
    administrator only for the install steps that require it.

    On Uninstall: removes this peer's tunnel and its wgflow backup
    files. With -RemoveWireGuardClient, also removes the WireGuard
    client itself (which removes ALL tunnels, including non-wgflow
    ones — there is a confirmation prompt).

.PARAMETER Action
    Install (default), Uninstall, or Update. Update is identical to
    Install — both replace any existing tunnel with this peer name.

.PARAMETER RemoveWireGuardClient
    Only meaningful with -Action Uninstall. Removes the WireGuard
    Windows client entirely. Prompts for confirmation.

.PARAMETER NoLog
    Suppress writing to %LOCALAPPDATA%\wgflow\install.log. Useful for
    one-off runs from a terminal where you only want console output.

.EXAMPLE
    # Default — install the tunnel.
    .\__PEER_NAME__-install.ps1

.EXAMPLE
    # Remove just this peer's tunnel.
    .\__PEER_NAME__-install.ps1 -Action Uninstall

.EXAMPLE
    # Remove this peer's tunnel AND the WireGuard client (full clean).
    .\__PEER_NAME__-install.ps1 -Action Uninstall -RemoveWireGuardClient

.NOTES
    Generated by wgflow. This script contains the peer's VPN private
    key — treat it like a password.
#>

[CmdletBinding()]
param(
    [ValidateSet('Install', 'Uninstall', 'Update')]
    [string]$Action = 'Install',
    [switch]$RemoveWireGuardClient,
    [switch]$NoLog
)

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
$PeerName     = '__PEER_NAME__'
$WgInstallDir = "$env:ProgramFiles\WireGuard"
$WgExe        = "$WgInstallDir\wireguard.exe"
$InstallerUrl = 'https://download.wireguard.com/windows-client/wireguard-installer.exe'

$WgflowDir       = Join-Path $env:LOCALAPPDATA 'wgflow'
$WgflowBackupDir = Join-Path $env:LOCALAPPDATA 'wgflow-backups'
$LogPath         = Join-Path $WgflowDir 'install.log'
$LogKeep         = 5

# Embedded WireGuard config (base64).
$ConfBase64 = @'
__CONF_BASE64__
'@

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
function Initialize-Log {
    if ($NoLog) { return }
    try {
        if (-not (Test-Path -LiteralPath $WgflowDir)) {
            New-Item -ItemType Directory -Path $WgflowDir -Force | Out-Null
        }
        # Rotate: install.log -> install.log.1 -> install.log.2 -> ...
        # Keep the most recent $LogKeep + the current one.
        if (Test-Path -LiteralPath $LogPath) {
            $size = (Get-Item -LiteralPath $LogPath).Length
            # Rotate only if the log has grown past 64 KB. Tiny logs
            # don't need rotation and keep the recent history readable.
            if ($size -gt 65536) {
                for ($i = $LogKeep; $i -gt 0; $i--) {
                    $src = "$LogPath.$($i - 1)"
                    $dst = "$LogPath.$i"
                    if ($i -eq 1) { $src = $LogPath }
                    if (Test-Path -LiteralPath $src) {
                        Move-Item -LiteralPath $src -Destination $dst -Force -ErrorAction SilentlyContinue
                    }
                }
            }
        }
    } catch {
        # Logging is best-effort — never let a log failure abort the install.
        Write-Host "warn: could not initialize log: $($_.Exception.Message)" -ForegroundColor Yellow
    }
}

function Write-Log {
    param([string]$Level, [string]$Message)
    $ts   = (Get-Date).ToString('yyyy-MM-dd HH:mm:ss')
    $line = "[$ts] [$Level] [$PeerName] $Message"

    # Console — color by level.
    $color = switch ($Level) {
        'ERR'  { 'Red' }
        'WARN' { 'Yellow' }
        'OK'   { 'Green' }
        default { 'White' }
    }
    Write-Host $line -ForegroundColor $color

    if (-not $NoLog) {
        try {
            Add-Content -LiteralPath $LogPath -Value $line -Encoding UTF8 -ErrorAction SilentlyContinue
        } catch {}
    }
}

# ---------------------------------------------------------------------------
# Admin / elevation
# ---------------------------------------------------------------------------
function Test-IsAdmin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

# Re-launch this script elevated, preserving the original arguments.
# Returns to the caller in the unelevated process so it can exit cleanly
# while the elevated copy continues.
function Invoke-Elevated {
    Write-Log 'INFO' "elevating to administrator for $Action"
    $argList = @(
        '-NoProfile',
        '-ExecutionPolicy', 'Bypass',
        '-File', "`"$PSCommandPath`"",
        '-Action', $Action
    )
    if ($RemoveWireGuardClient) { $argList += '-RemoveWireGuardClient' }
    if ($NoLog)                 { $argList += '-NoLog' }
    try {
        Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $argList -Wait
    } catch {
        Write-Log 'ERR' "elevation denied or failed: $($_.Exception.Message)"
        exit 10
    }
}

# ---------------------------------------------------------------------------
# WireGuard detection
# ---------------------------------------------------------------------------
function Test-WireGuardInstalled {
    # Machine-wide (default) — exe + registry uninstall entry.
    if (Test-Path -LiteralPath $WgExe) { return $true }
    $regRoots = @(
        'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall',
        'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall',
        'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'
    )
    foreach ($root in $regRoots) {
        if (-not (Test-Path -LiteralPath $root)) { continue }
        $entries = Get-ChildItem -LiteralPath $root -ErrorAction SilentlyContinue
        foreach ($e in $entries) {
            $props = Get-ItemProperty -LiteralPath $e.PsPath -ErrorAction SilentlyContinue
            if ($props.DisplayName -and $props.DisplayName -like 'WireGuard*') { return $true }
        }
    }
    return $false
}

function Install-WireGuard {
    if (-not (Test-IsAdmin)) {
        Write-Log 'ERR' 'cannot install WireGuard without administrator privileges'
        return $false
    }
    Write-Log 'INFO' 'downloading the latest WireGuard installer'
    $tempInstaller = Join-Path $env:TEMP 'wireguard-installer.exe'
    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $InstallerUrl -OutFile $tempInstaller -UseBasicParsing
    } catch {
        Write-Log 'ERR' "download failed: $($_.Exception.Message)"
        return $false
    }
    Write-Log 'INFO' 'running silent install (this may take 30-60 seconds)'
    try {
        $proc = Start-Process -FilePath $tempInstaller -ArgumentList '/S' -Wait -PassThru
    } catch {
        Write-Log 'ERR' "installer launch failed: $($_.Exception.Message)"
        return $false
    } finally {
        Remove-Item -LiteralPath $tempInstaller -Force -ErrorAction SilentlyContinue
    }
    if ($proc.ExitCode -ne 0) {
        Write-Log 'ERR' "WireGuard installer exited $($proc.ExitCode)"
        return $false
    }
    if (-not (Test-Path -LiteralPath $WgExe)) {
        Write-Log 'ERR' "installer ran but $WgExe is still missing"
        return $false
    }
    Write-Log 'OK' 'WireGuard installed'
    return $true
}

function Uninstall-WireGuardClient {
    # Find the uninstall string in the registry and run it silently.
    $regRoots = @(
        'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall',
        'HKLM:\SOFTWARE\WOW6432Node\Microsoft\Windows\CurrentVersion\Uninstall',
        'HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall'
    )
    foreach ($root in $regRoots) {
        if (-not (Test-Path -LiteralPath $root)) { continue }
        $entries = Get-ChildItem -LiteralPath $root -ErrorAction SilentlyContinue
        foreach ($e in $entries) {
            $props = Get-ItemProperty -LiteralPath $e.PsPath -ErrorAction SilentlyContinue
            if ($props.DisplayName -and $props.DisplayName -like 'WireGuard*' -and $props.UninstallString) {
                Write-Log 'INFO' "running WireGuard uninstaller: $($props.UninstallString)"
                $cmd = $props.UninstallString
                # Some uninstallers wrap the path in quotes; split off args.
                if ($cmd -match '^"([^"]+)"\s*(.*)$') {
                    $exe = $matches[1]
                    $args = $matches[2]
                } elseif ($cmd -match '^(\S+)\s*(.*)$') {
                    $exe = $matches[1]
                    $args = $matches[2]
                } else {
                    $exe = $cmd
                    $args = ''
                }
                $argList = @()
                if ($args) { $argList += $args -split ' ' | Where-Object { $_ } }
                $argList += '/S'   # silent
                try {
                    Start-Process -FilePath $exe -ArgumentList $argList -Wait
                    Write-Log 'OK' 'WireGuard client removed'
                    return $true
                } catch {
                    Write-Log 'ERR' "uninstaller failed: $($_.Exception.Message)"
                    return $false
                }
            }
        }
    }
    Write-Log 'WARN' 'no WireGuard uninstall entry found — already gone?'
    return $true
}

# ---------------------------------------------------------------------------
# Tunnel ops
# ---------------------------------------------------------------------------
function Backup-ExistingTunnel {
    # WireGuard's own config store is under %ProgramFiles%\WireGuard\Data\
    # Configurations\, admin-only readable. We can't get the raw file
    # without elevation, but we ALSO can't read the running tunnel's
    # config back via wireguard.exe — there's no /showtunnel CLI on
    # Windows. So the backup we do is: noting that a same-named tunnel
    # existed, and stamping a marker file in user space. The user can
    # check it later if they want to know what was overwritten.
    if (-not (Test-Path -LiteralPath $WgflowBackupDir)) {
        try {
            New-Item -ItemType Directory -Path $WgflowBackupDir -Force | Out-Null
        } catch {
            Write-Log 'WARN' "could not create backup dir: $($_.Exception.Message)"
            return
        }
    }
    $ts = (Get-Date).ToString('yyyyMMdd-HHmmss')
    $marker = Join-Path $WgflowBackupDir "$PeerName-$ts.replaced.txt"
    $info = @(
        "wgflow installer replaced an existing tunnel with this name."
        "Peer:           $PeerName"
        "Replaced at:    $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')"
        "Previous data:  WireGuard's own config store at"
        "                C:\Program Files\WireGuard\Data\Configurations\"
        "                holds the previous .conf (admin-only readable)."
        "                If you need to recover it, look there before"
        "                running this script again — once the tunnel"
        "                service is reinstalled, the old config is gone."
    ) -join "`r`n"
    try {
        Set-Content -LiteralPath $marker -Value $info -Encoding UTF8
        Write-Log 'INFO' "left replacement marker: $marker"
    } catch {
        Write-Log 'WARN' "could not write marker: $($_.Exception.Message)"
    }
}

function Test-TunnelExists {
    # WireGuard installs each tunnel as a Windows service named
    # "WireGuardTunnel$<name>". Checking the service is the most
    # reliable detector across versions.
    $svc = Get-Service -Name "WireGuardTunnel`$$PeerName" -ErrorAction SilentlyContinue
    return $null -ne $svc
}

function Install-Tunnel {
    $confPath = Join-Path $env:TEMP "$PeerName.conf"
    try {
        $confBytes = [Convert]::FromBase64String($ConfBase64.Trim())
        [System.IO.File]::WriteAllBytes($confPath, $confBytes)
    } catch {
        Write-Log 'ERR' "failed to decode embedded config: $($_.Exception.Message)"
        return $false
    }

    # Remove any existing tunnel with this name. Idempotent — exits
    # non-zero if there's nothing to remove, which is fine.
    $null = & $WgExe '/uninstalltunnelservice' $PeerName 2>&1
    Start-Sleep -Seconds 1

    Write-Log 'INFO' "installing tunnel service for $PeerName"
    $output = & $WgExe '/installtunnelservice' $confPath 2>&1
    $exit = $LASTEXITCODE
    Remove-Item -LiteralPath $confPath -Force -ErrorAction SilentlyContinue
    if ($exit -ne 0) {
        Write-Log 'ERR' "tunnel install failed (exit $exit): $output"
        return $false
    }
    Write-Log 'OK' "tunnel $PeerName installed and active"
    return $true
}

function Remove-Tunnel {
    if (-not (Test-TunnelExists)) {
        Write-Log 'WARN' "tunnel $PeerName not present — nothing to remove"
        return $true
    }
    Write-Log 'INFO' "removing tunnel $PeerName"
    $output = & $WgExe '/uninstalltunnelservice' $PeerName 2>&1
    $exit = $LASTEXITCODE
    if ($exit -ne 0) {
        Write-Log 'ERR' "tunnel uninstall failed (exit $exit): $output"
        return $false
    }
    Write-Log 'OK' "tunnel $PeerName removed"

    # Clean up any wgflow markers for this peer.
    if (Test-Path -LiteralPath $WgflowBackupDir) {
        Get-ChildItem -LiteralPath $WgflowBackupDir -Filter "$PeerName-*.replaced.txt" -ErrorAction SilentlyContinue |
            ForEach-Object {
                Remove-Item -LiteralPath $_.FullName -Force -ErrorAction SilentlyContinue
                Write-Log 'INFO' "cleaned up marker $($_.Name)"
            }
    }
    return $true
}

# ---------------------------------------------------------------------------
# Entry points (one per Action)
# ---------------------------------------------------------------------------
function Do-Install {
    # User-context phase: detection + backup planning.
    if (-not (Test-WireGuardInstalled)) {
        Write-Log 'INFO' 'WireGuard client not detected — will install'
        $needsElevation = $true
    } else {
        Write-Log 'INFO' 'WireGuard client already installed'
        $needsElevation = $false
    }

    # The tunnel install ALWAYS needs admin (service creation).
    $needsElevation = $true

    if (Test-TunnelExists) {
        Write-Log 'INFO' "existing tunnel $PeerName will be replaced"
        Backup-ExistingTunnel
    }

    if (-not (Test-IsAdmin)) {
        if ($needsElevation) {
            Invoke-Elevated
            return  # The elevated process did the real work.
        }
    }

    # Elevated phase.
    if (-not (Test-WireGuardInstalled)) {
        if (-not (Install-WireGuard)) {
            exit 20
        }
    }
    if (-not (Install-Tunnel)) {
        exit 30
    }
    Write-Log 'OK' "$Action complete"
}

function Do-Uninstall {
    if (-not (Test-IsAdmin)) {
        Invoke-Elevated
        return
    }
    # Elevated phase.
    if (-not (Test-WireGuardInstalled)) {
        Write-Log 'WARN' 'WireGuard not installed — nothing to do'
        return
    }
    Remove-Tunnel | Out-Null

    if ($RemoveWireGuardClient) {
        Write-Host ""
        Write-Host "==============================================" -ForegroundColor Yellow
        Write-Host "  WARNING" -ForegroundColor Yellow
        Write-Host "  -RemoveWireGuardClient was specified." -ForegroundColor Yellow
        Write-Host "  This will remove the WireGuard client entirely," -ForegroundColor Yellow
        Write-Host "  including any OTHER tunnels you may have set up" -ForegroundColor Yellow
        Write-Host "  outside of wgflow." -ForegroundColor Yellow
        Write-Host "==============================================" -ForegroundColor Yellow
        Write-Host ""
        $confirm = Read-Host "type REMOVE to confirm, anything else to cancel"
        if ($confirm -ne 'REMOVE') {
            Write-Log 'INFO' 'WireGuard client removal cancelled by user'
            return
        }
        if (-not (Uninstall-WireGuardClient)) {
            exit 40
        }
    }
    Write-Log 'OK' 'Uninstall complete'
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
Initialize-Log
Write-Log 'INFO' "starting Action=$Action"

switch ($Action) {
    'Install'   { Do-Install }
    'Update'    { Do-Install }   # alias
    'Uninstall' { Do-Uninstall }
}
"""


def render_install_script_user_context(peer_name: str, conf_text: str) -> str:
    """Render the user-context variant of the .ps1 installer (v4.4.0+).

    Same embedding mechanism as render_install_script (peer config as
    wrapped base64), different template — see _PS1_USER_TEMPLATE for
    the full rationale. Caller wraps neither in a zip nor in a
    passphrase: this variant is meant for direct HTTPS download from
    the panel by an authenticated user.

    Raises ValueError on unsafe peer names.
    """
    if not peer_name or not _SAFE_NAME_RE.match(peer_name):
        raise ValueError(
            f"unsafe peer name {peer_name!r} for installer script — must "
            f"match {_SAFE_NAME_RE.pattern}"
        )
    raw_b64 = base64.b64encode(conf_text.encode("utf-8")).decode("ascii")
    wrapped = "\n".join(raw_b64[i:i + 76] for i in range(0, len(raw_b64), 76))
    return (
        _PS1_USER_TEMPLATE
        .replace("__PEER_NAME__", peer_name)
        .replace("__CONF_BASE64__", wrapped)
    )
