"""Per-peer PowerShell installer generator + zip packager.

Renders a self-contained .ps1 script with the WireGuard config embedded as
base64. The .ps1 is then wrapped in an AES-256 encrypted zip with an
auto-generated passphrase, suitable for emailing.

Workflow:
  1. UI calls render_install_script(name, conf) -> .ps1 text with conf embedded
  2. UI calls package_install_zip(name, ps1, password) -> (zip bytes, filename)
  3. Browser downloads the zip; UI shows the passphrase to the operator
  4. Operator emails the zip and communicates the passphrase via a
     separate channel (SMS, Signal, in person)
  5. Recipient extracts with 7-Zip (native Windows zip UI does NOT support
     AES-encrypted zips), runs the .ps1, and is on the VPN

The .ps1 itself contains the peer's private key in base64 — the encrypted
zip is the only thing protecting it. This is acceptable for the email-
based distribution flow but means the .ps1 must never be distributed
unencrypted.
"""
from __future__ import annotations

import base64
import io
import re
import secrets
from typing import Tuple

import pyzipper

# ---------------------------------------------------------------------------
# Wordlist for passphrase generation. A curated subset of common short
# English words. Each word ≤ 6 characters, easy to communicate verbally
# (no homophones, no ambiguous spellings). 200+ words → ~7.6 bits/word.
# 8 words → ~61 bits, plenty against offline brute-force on AES-256 zip.
# ---------------------------------------------------------------------------

_WORDS = """
acid acre actor adult agent aim album alert alley amber angle ankle apple
arch arena army arrow ash aunt auto axis baby back bag bake band bank bar
bark barn base bath bay beam bean bear beat bed bee beef bell belly belt bench
bend berry best bet bib bid big bike bill bin bird birth bit bite black blade
blame blank blast bless blind block blood blow blue blur board boat body bold
bolt bone book boom boot born boss both bow bowl box boy brain brake branch
brand brave bread break breed brick bride brief bring broad broom brown brush
bubble buddy bug build bull bun bunch burn bus bush buyer cab cabin cake
calf call calm camp can cap car card care carry cart case cash cast cat catch
cause cave cell cent chain chair chalk champ chance change charge chart chase
chat cheap cheek cheese chef chess chest chick chief chili chin chip chirp
choice chop church cigar cinch city civic clamp clap clash class claw clay
clean clear clerk click cliff climb clip clock clog close cloth cloud clown
club coach coal coast cob code coffee coin cold color comb come cone cook
copper copy cord cork corn cost couch cough count couple court cousin cover
cowbell crab craft crane crash crawl craze crazy cream crew cried crispy
crook crop cross crow crowd crown crush crust crypt cup cure curl curry
cut cute cycle dad daily dairy daisy dance darken dash data date dawn deaf
deal death debate debit debt decaf decay decide decoy deduct deed deep
deer defrost defuse degree delete deli delta demote denial dense
"""

_WORDLIST = [w for w in _WORDS.split() if w]
assert len(_WORDLIST) >= 200, f"wordlist too short: {len(_WORDLIST)}"


def generate_passphrase(words: int = 8) -> str:
    """Generate a Diceware-style passphrase using cryptographic randomness.

    Hyphen-separated so word boundaries are unambiguous when communicated
    via SMS / verbal channels.
    """
    return "-".join(secrets.choice(_WORDLIST) for _ in range(words))


# ---------------------------------------------------------------------------
# PowerShell script template
# ---------------------------------------------------------------------------
# Two substitutions: __PEER_NAME__ and __CONF_BASE64__.
# Use str.replace (not .format) so {} characters in PowerShell are safe.

_PS1_TEMPLATE = r"""# wgflow client installer for peer: __PEER_NAME__
#
# This script is self-contained: the WireGuard configuration is embedded
# inside it (base64-encoded). On run the script:
#   1. Self-elevates to administrator
#   2. Installs the WireGuard client if it isn't already
#   3. Removes any existing tunnel named "__PEER_NAME__"
#   4. Writes the embedded config and starts the tunnel
#
# Re-run any time the wgflow admin sends you a new copy.
#
# WARNING: this script contains your VPN private key. Treat it like a
# password — do not share, do not commit to source control. The encrypted
# zip you received this in is the protection; once extracted, this file
# is sensitive.
#
# Generated by wgflow.

$ErrorActionPreference = 'Stop'

# ---------------------------------------------------------------------------
# Self-elevate to administrator if we aren't already.
# ---------------------------------------------------------------------------
function Test-IsAdmin {
    $id = [Security.Principal.WindowsIdentity]::GetCurrent()
    $p  = New-Object Security.Principal.WindowsPrincipal($id)
    return $p.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
}

if (-not (Test-IsAdmin)) {
    Write-Host "Re-launching with administrator privileges..." -ForegroundColor Yellow
    $argList = @(
        '-NoProfile',
        '-ExecutionPolicy', 'Bypass',
        '-File', "`"$PSCommandPath`""
    )
    Start-Process -FilePath 'powershell.exe' -Verb RunAs -ArgumentList $argList
    exit
}

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------
$PeerName     = '__PEER_NAME__'
$ConfPath     = Join-Path $env:TEMP "$PeerName.conf"
$WgInstallDir = "$env:ProgramFiles\WireGuard"
$WgExe        = "$WgInstallDir\wireguard.exe"
$InstallerUrl = 'https://download.wireguard.com/windows-client/wireguard-installer.exe'

# Embedded WireGuard config (base64).
$ConfBase64 = @'
__CONF_BASE64__
'@

Write-Host ""
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host "  wgflow client installer" -ForegroundColor Cyan
Write-Host "  peer: $PeerName" -ForegroundColor Cyan
Write-Host "==============================================" -ForegroundColor Cyan
Write-Host ""

# ---------------------------------------------------------------------------
# 1. Install WireGuard if missing
# ---------------------------------------------------------------------------
function Test-WireGuardInstalled {
    if (Test-Path -LiteralPath $WgExe) { return $true }
    $regKeys = @(
        'HKLM:\SOFTWARE\WireGuard',
        'HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\WireGuard'
    )
    foreach ($k in $regKeys) {
        if (Test-Path -LiteralPath $k) { return $true }
    }
    return $false
}

if (Test-WireGuardInstalled) {
    Write-Host "[1/4] WireGuard is already installed." -ForegroundColor Green
} else {
    Write-Host "[1/4] WireGuard not found - downloading the latest installer..." -ForegroundColor Yellow
    $tempInstaller = Join-Path $env:TEMP 'wireguard-installer.exe'
    try {
        [Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls12
        Invoke-WebRequest -Uri $InstallerUrl -OutFile $tempInstaller -UseBasicParsing
    } catch {
        Write-Host "ERROR: failed to download WireGuard installer." -ForegroundColor Red
        Write-Host "  $($_.Exception.Message)" -ForegroundColor Red
        Read-Host "Press Enter to exit"
        exit 1
    }

    Write-Host "      installing silently (this may take 30-60 seconds)..." -ForegroundColor Yellow
    $proc = Start-Process -FilePath $tempInstaller -ArgumentList '/S' -Wait -PassThru
    Remove-Item -LiteralPath $tempInstaller -Force -ErrorAction SilentlyContinue

    if ($proc.ExitCode -ne 0) {
        Write-Host "ERROR: WireGuard installer exited with code $($proc.ExitCode)." -ForegroundColor Red
        Read-Host "Press Enter to exit"
        exit 1
    }

    if (-not (Test-Path -LiteralPath $WgExe)) {
        Write-Host "ERROR: installer ran but $WgExe is still missing." -ForegroundColor Red
        Read-Host "Press Enter to exit"
        exit 1
    }
    Write-Host "      installed OK." -ForegroundColor Green
}

# ---------------------------------------------------------------------------
# 2. Decode + write the embedded config
# ---------------------------------------------------------------------------
Write-Host "[2/4] Writing config to $ConfPath..." -ForegroundColor Yellow
try {
    $confBytes = [Convert]::FromBase64String($ConfBase64.Trim())
    [System.IO.File]::WriteAllBytes($ConfPath, $confBytes)
} catch {
    Write-Host "ERROR: failed to decode embedded config: $($_.Exception.Message)" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

# ---------------------------------------------------------------------------
# 3. Remove any existing tunnel with this name (idempotent upgrade path)
# ---------------------------------------------------------------------------
Write-Host "[3/4] Removing any existing tunnel named '$PeerName'..." -ForegroundColor Yellow
$null = & $WgExe '/uninstalltunnelservice' $PeerName 2>&1
Start-Sleep -Seconds 2

# ---------------------------------------------------------------------------
# 4. Install + start the new tunnel
# ---------------------------------------------------------------------------
Write-Host "[4/4] Installing tunnel..." -ForegroundColor Yellow
$installOutput = & $WgExe '/installtunnelservice' $ConfPath 2>&1
$installExit = $LASTEXITCODE

# Wipe the temp conf — WireGuard's tunnel service has its own copy now,
# and we don't want the unencrypted .conf left in %TEMP%.
Remove-Item -LiteralPath $ConfPath -Force -ErrorAction SilentlyContinue

if ($installExit -ne 0) {
    Write-Host "ERROR: tunnel install failed (exit $installExit):" -ForegroundColor Red
    Write-Host "  $installOutput" -ForegroundColor Red
    Read-Host "Press Enter to exit"
    exit 1
}

Write-Host ""
Write-Host "==============================================" -ForegroundColor Green
Write-Host "  SUCCESS" -ForegroundColor Green
Write-Host "  Tunnel '$PeerName' is installed and active." -ForegroundColor Green
Write-Host "  Open the WireGuard app to view status." -ForegroundColor Green
Write-Host "==============================================" -ForegroundColor Green
Write-Host ""
Read-Host "Press Enter to exit"
"""


_SAFE_NAME_RE = re.compile(r"^[A-Za-z0-9._-]+$")


def render_install_script(peer_name: str, conf_text: str) -> str:
    """Render a self-contained .ps1 with the WireGuard config embedded as base64.

    Raises ValueError on unsafe peer names (anything that could break the
    PowerShell single-quote literal we interpolate it into).
    """
    if not peer_name or not _SAFE_NAME_RE.match(peer_name):
        raise ValueError(
            f"unsafe peer name {peer_name!r} for installer script — must "
            f"match {_SAFE_NAME_RE.pattern}"
        )
    raw_b64 = base64.b64encode(conf_text.encode("utf-8")).decode("ascii")
    wrapped = "\n".join(raw_b64[i:i + 76] for i in range(0, len(raw_b64), 76))
    return (
        _PS1_TEMPLATE
        .replace("__PEER_NAME__", peer_name)
        .replace("__CONF_BASE64__", wrapped)
    )


# ---------------------------------------------------------------------------
# Zip packaging — AES-256
# ---------------------------------------------------------------------------

def package_install_zip(
    peer_name: str, ps1_text: str, password: str
) -> Tuple[bytes, str]:
    """Wrap the .ps1 in a single-entry AES-256 encrypted zip.

    AES-256 is required because the .ps1 contains the peer's private key
    and legacy ZipCrypto is recoverable in seconds via known-plaintext
    attacks (a script with a predictable preamble is the textbook case).

    Trade-off: native Windows zip UI cannot extract AES-encrypted zips;
    recipients need 7-Zip installed. The wgflow UI surfaces this fact
    when showing the passphrase.

    Returns (zip_bytes, inner_filename).
    """
    buf = io.BytesIO()
    inner_filename = f"{peer_name}-install.ps1"

    with pyzipper.AESZipFile(
        buf, mode="w",
        compression=pyzipper.ZIP_DEFLATED,
        encryption=pyzipper.WZ_AES,
    ) as zf:
        zf.setpassword(password.encode("utf-8"))
        zf.writestr(inner_filename, ps1_text)

    return buf.getvalue(), inner_filename
